name: Taxi-Booking Real-Time Project

on:
    push:
        branches: 
            - main
    workflow_dispatch:
      
jobs:
  build:
    name: runs on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: clean package
        run: mvn clean 
        working-directory: ./taxi-booking
      - name: Test Package
        run: mvn test
        working-directory: ./taxi-booking
      - name: build package
        run: mvn package
        working-directory: ./taxi-booking
    #   - name: Publish Test Report
    #     uses: dorny/test-reporter@v1
    #     if: always()
    #     with:
    #       name: Maven Tests
    #       path: target/surefire-reports/*.xml
    #       reporter: java-junit
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: taxi-booking-war
          path: target/taxi-booking-1.0.1.war